version: '3.8'

services:
  nginx:
    container_name: nginx-project
    build:
      context: ./docker/nginx
    volumes:
      - ./app:/var/www/hw-otus
      - ./docker/nginx/config/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8787:80"

  php-fpm:
    container_name: php-fpm-project
    build:
      context: ./docker/php-fpm
    volumes:
      - ./app:/var/www/hw-otus
